FROM node:alpine
WORKDIR /app
COPY package.json /app
RUN npm config set registry http://registry.npmjs.org
RUN npm install -g http-server
RUN npm install
COPY . /app
EXPOSE 8080
RUN npm run build
CMD [ "http-server", "dist" ]