
FROM node:alpine

# Create app directory
WORKDIR /server

# Install app dependencies
COPY package.json /server
RUN npm install

# Bundle app source
COPY . /server

RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
RUN npm install --quiet node-gyp -g

EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]
