FROM node:alpine
WORKDIR /app
RUN apk add python3 py3-pip
RUN npm install --quiet node-gyp -g
COPY package.json /app
#RUN npm config set registry http://registry.npmjs.org
#RUN npm install
COPY . /app
EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]